export var seat = {
  seatGrade: [
    { seatGrade: "common", codNm: "일반석" },
    { seatGrade: "unique", codNm: "특화석" },
    { seatGrade: "SKYBOX", codNm: "스카이박스(10인)" },
  ],
  seatName: [
    /* 일반석 */
    { seatGrade: "common", seatName: "1", codNm: "좌석선택" },
    { seatGrade: "common", seatName: "2", codNm: "내야지정석(1F)" },
    { seatGrade: "common", seatName: "3", codNm: "내야지정석(2F)" },
    { seatGrade: "common", seatName: "4", codNm: "외야커플석" },
    { seatGrade: "common", seatName: "5", codNm: "외야지정석" },
    /*특화석 */
    { seatGrade: "unique", seatName: "1", codNm: "포수후면석" },
    { seatGrade: "unique", seatName: "2", codNm: "중앙탁자석" },
    { seatGrade: "unique", seatName: "3", codNm: "중앙탁자석A" },
    { seatGrade: "unique", seatName: "4", codNm: "중앙가족석" },
    { seatGrade: "unique", seatName: "5", codNm: "내야응원단석" },
    { seatGrade: "unique", seatName: "6", codNm: "내야탁자석" },
    { seatGrade: "unique", seatName: "7", codNm: "내야하단탁자석" },
    { seatGrade: "unique", seatName: "8", codNm: "중앙메디칼존(내야커플석)" },
    { seatGrade: "unique", seatName: "9", codNm: "VIP커플석" },
    { seatGrade: "unique", seatName: "10", codNm: "덕아웃지정석" },
    { seatGrade: "unique", seatName: "11", codNm: "익사이팅존" },
    { seatGrade: "unique", seatName: "12", codNm: "익사이팅커플석" },
    { seatGrade: "unique", seatName: "13", codNm: "불펜지정석" },
    { seatGrade: "unique", seatName: "14", codNm: "외야라운지석" },
    { seatGrade: "unique", seatName: "15", codNm: "스테이인터뷰존" },
    { seatGrade: "unique", seatName: "16", codNm: "잔디석" },
    { seatGrade: "unique", seatName: "17", codNm: "필드박스(1인)" },
    { seatGrade: "unique", seatName: "18", codNm: "미니박스" },
    /*스카이박스*/
    { seatGrade: "SKYBOX", seatName: "1", codNm: "스카이박스(10인)" },
  ],

  seatNum: [
    /* 내야지정석 (1F) */
    { seatGrade: "common", seatName: "2", seatNum: "101", codNm: "101" },
    { seatGrade: "common", seatName: "2", seatNum: "102", codNm: "102" },
    { seatGrade: "common", seatName: "2", seatNum: "103", codNm: "103" },
    { seatGrade: "common", seatName: "2", seatNum: "104", codNm: "104" },
    { seatGrade: "common", seatName: "2", seatNum: "105", codNm: "105" },
    { seatGrade: "common", seatName: "2", seatNum: "111", codNm: "111" },
    { seatGrade: "common", seatName: "2", seatNum: "112", codNm: "112" },
    { seatGrade: "common", seatName: "2", seatNum: "301", codNm: "301" },
    { seatGrade: "common", seatName: "2", seatNum: "302", codNm: "302" },
    { seatGrade: "common", seatName: "2", seatNum: "303", codNm: "303" },
    { seatGrade: "common", seatName: "2", seatNum: "304", codNm: "304" },
    { seatGrade: "common", seatName: "2", seatNum: "305", codNm: "305" },
    { seatGrade: "common", seatName: "2", seatNum: "311", codNm: "311" },
    { seatGrade: "common", seatName: "2", seatNum: "312", codNm: "312" },
    { seatGrade: "common", seatName: "2", seatNum: "313", codNm: "313" },
    { seatGrade: "common", seatName: "2", seatNum: "314", codNm: "314" },
    { seatGrade: "common", seatName: "2", seatNum: "315", codNm: "315" },
    { seatGrade: "common", seatName: "2", seatNum: "316", codNm: "316" },
    { seatGrade: "common", seatName: "2", seatNum: "317", codNm: "317" },
    { seatGrade: "common", seatName: "2", seatNum: "318", codNm: "318" },
    { seatGrade: "common", seatName: "2", seatNum: "319", codNm: "319" },
    { seatGrade: "common", seatName: "2", seatNum: "320", codNm: "320" },
    /* 내야지정석 (2F) */
    { seatGrade: "common", seatName: "3", seatNum: "201", codNm: "201" },
    { seatGrade: "common", seatName: "3", seatNum: "202", codNm: "202" },
    { seatGrade: "common", seatName: "3", seatNum: "203", codNm: "203" },
    { seatGrade: "common", seatName: "3", seatNum: "204", codNm: "204" },
    { seatGrade: "common", seatName: "3", seatNum: "205", codNm: "205" },
    { seatGrade: "common", seatName: "3", seatNum: "206", codNm: "206" },
    { seatGrade: "common", seatName: "3", seatNum: "207", codNm: "207" },
    { seatGrade: "common", seatName: "3", seatNum: "208", codNm: "208" },
    { seatGrade: "common", seatName: "3", seatNum: "209", codNm: "209" },
    { seatGrade: "common", seatName: "3", seatNum: "401", codNm: "401" },
    { seatGrade: "common", seatName: "3", seatNum: "402", codNm: "402" },
    { seatGrade: "common", seatName: "3", seatNum: "403", codNm: "403" },
    { seatGrade: "common", seatName: "3", seatNum: "404", codNm: "404" },
    { seatGrade: "common", seatName: "3", seatNum: "405", codNm: "405" },
    { seatGrade: "common", seatName: "3", seatNum: "406", codNm: "406" },
    { seatGrade: "common", seatName: "3", seatNum: "407", codNm: "407" },
    { seatGrade: "common", seatName: "3", seatNum: "408", codNm: "408" },
    { seatGrade: "common", seatName: "3", seatNum: "409", codNm: "409" },
    /*외야 커플석 */
    { seatGrade: "common", seatName: "4", seatNum: "122", codNm: "122" },
    { seatGrade: "common", seatName: "4", seatNum: "123", codNm: "123" },
    { seatGrade: "common", seatName: "4", seatNum: "124", codNm: "124" },
    { seatGrade: "common", seatName: "4", seatNum: "125", codNm: "125" },
    { seatGrade: "common", seatName: "4", seatNum: "126", codNm: "126" },
    { seatGrade: "common", seatName: "4", seatNum: "127", codNm: "127" },
    /*외야 지정석*/
    { seatGrade: "common", seatName: "5", seatNum: "121", codNm: "121" },
    { seatGrade: "common", seatName: "5", seatNum: "122", codNm: "122" },
    { seatGrade: "common", seatName: "5", seatNum: "123", codNm: "123" },
    { seatGrade: "common", seatName: "5", seatNum: "124", codNm: "124" },
    { seatGrade: "common", seatName: "5", seatNum: "125", codNm: "125" },
    { seatGrade: "common", seatName: "5", seatNum: "126", codNm: "126" },
    { seatGrade: "common", seatName: "5", seatNum: "127", codNm: "127" },
    /* 포수후면석 (라이프플러스존) */
    { seatGrade: "unique", seatName: "1", seatNum: "S01", codNm: "S01" },
    { seatGrade: "unique", seatName: "1", seatNum: "S02", codNm: "S02" },
    { seatGrade: "unique", seatName: "1", seatNum: "S03", codNm: "S03" },
    { seatGrade: "unique", seatName: "1", seatNum: "S04", codNm: "S04" },
    { seatGrade: "unique", seatName: "1", seatNum: "S05", codNm: "S05" },
    /* 중앙탁자석 */
    { seatGrade: "unique", seatName: "2", seatNum: "A01", codNm: "A01" },
    { seatGrade: "unique", seatName: "2", seatNum: "A02", codNm: "A02" },
    { seatGrade: "unique", seatName: "2", seatNum: "A03", codNm: "A03" },
    { seatGrade: "unique", seatName: "2", seatNum: "A04", codNm: "A04" },
    { seatGrade: "unique", seatName: "2", seatNum: "A05", codNm: "A05" },
    /* 중앙탁자석 A */
    { seatGrade: "unique", seatName: "3", seatNum: "A01", codNm: "A01" },
    { seatGrade: "unique", seatName: "3", seatNum: "A02", codNm: "A02" },
    { seatGrade: "unique", seatName: "3", seatNum: "A03", codNm: "A03" },
    { seatGrade: "unique", seatName: "3", seatNum: "A04", codNm: "A04" },
    { seatGrade: "unique", seatName: "3", seatNum: "A05", codNm: "A05" },
    /*중앙가족석 */
    { seatGrade: "unique", seatName: "4", seatNum: "A06", codNm: "A06" },
    { seatGrade: "unique", seatName: "4", seatNum: "A07", codNm: "A07" },
    /*내야응원단석*/
    { seatGrade: "unique", seatName: "5", seatNum: "113", codNm: "113" },
    { seatGrade: "unique", seatName: "5", seatNum: "114", codNm: "114" },
    { seatGrade: "unique", seatName: "5", seatNum: "115", codNm: "115" },
    { seatGrade: "unique", seatName: "5", seatNum: "116", codNm: "116" },
    /*내야탁자석 */
    { seatGrade: "unique", seatName: "6", seatNum: "100", codNm: "100" },
    { seatGrade: "unique", seatName: "6", seatNum: "300", codNm: "300" },
    /*내야하단탁자석 */
    { seatGrade: "unique", seatName: "7", seatNum: "110", codNm: "110" },
    { seatGrade: "unique", seatName: "7", seatNum: "111", codNm: "111" },
    { seatGrade: "unique", seatName: "7", seatNum: "112", codNm: "112" },
    { seatGrade: "unique", seatName: "7", seatNum: "310", codNm: "310" },
    { seatGrade: "unique", seatName: "7", seatNum: "311", codNm: "311" },
    { seatGrade: "unique", seatName: "7", seatNum: "312", codNm: "312" },
    { seatGrade: "unique", seatName: "7", seatNum: "313", codNm: "313" },
    { seatGrade: "unique", seatName: "7", seatNum: "314", codNm: "314" },
    { seatGrade: "unique", seatName: "7", seatNum: "315", codNm: "315" },
    { seatGrade: "unique", seatName: "7", seatNum: "316", codNm: "316" },
    { seatGrade: "unique", seatName: "7", seatNum: "317", codNm: "317" },
    { seatGrade: "unique", seatName: "7", seatNum: "318", codNm: "318" },
    { seatGrade: "unique", seatName: "7", seatNum: "319", codNm: "319" },
    { seatGrade: "unique", seatName: "7", seatNum: "320", codNm: "320" },
    /* 내야커플석 */
    { seatGrade: "unique", seatName: "8", seatNum: "111", codNm: "111" },
    { seatGrade: "unique", seatName: "8", seatNum: "112", codNm: "112" },
    { seatGrade: "unique", seatName: "8", seatNum: "311", codNm: "311" },
    { seatGrade: "unique", seatName: "8", seatNum: "312", codNm: "312" },
    { seatGrade: "unique", seatName: "8", seatNum: "313", codNm: "313" },
    { seatGrade: "unique", seatName: "8", seatNum: "314", codNm: "314" },
    { seatGrade: "unique", seatName: "8", seatNum: "315", codNm: "315" },
    { seatGrade: "unique", seatName: "8", seatNum: "316", codNm: "316" },
    { seatGrade: "unique", seatName: "8", seatNum: "317", codNm: "317" },
    { seatGrade: "unique", seatName: "8", seatNum: "318", codNm: "318" },
    { seatGrade: "unique", seatName: "8", seatNum: "319", codNm: "319" },
    { seatGrade: "unique", seatName: "8", seatNum: "320", codNm: "320" },
    /* vip커플석 */
    { seatGrade: "unique", seatName: "9", seatNum: "110", codNm: "110" },
    { seatGrade: "unique", seatName: "9", seatNum: "310", codNm: "310" },
    /* 덕아웃지정석 */
    { seatGrade: "unique", seatName: "10", seatNum: "110", codNm: "110" },
    { seatGrade: "unique", seatName: "10", seatNum: "310", codNm: "310" },
    /* 익사이팅존 */
    { seatGrade: "unique", seatName: "11", seatNum: "106", codNm: "106" },
    { seatGrade: "unique", seatName: "11", seatNum: "107", codNm: "107" },
    { seatGrade: "unique", seatName: "11", seatNum: "108", codNm: "108" },
    { seatGrade: "unique", seatName: "11", seatNum: "109", codNm: "109" },
    { seatGrade: "unique", seatName: "11", seatNum: "306", codNm: "306" },
    { seatGrade: "unique", seatName: "11", seatNum: "307", codNm: "307" },
    { seatGrade: "unique", seatName: "11", seatNum: "308", codNm: "308" },
    { seatGrade: "unique", seatName: "11", seatNum: "309", codNm: "309" },
    /* 익사이팅커플석 */
    { seatGrade: "unique", seatName: "12", seatNum: "106", codNm: "106" },
    { seatGrade: "unique", seatName: "12", seatNum: "107", codNm: "107" },
    { seatGrade: "unique", seatName: "12", seatNum: "108", codNm: "108" },
    { seatGrade: "unique", seatName: "12", seatNum: "109", codNm: "109" },
    { seatGrade: "unique", seatName: "12", seatNum: "306", codNm: "306" },
    { seatGrade: "unique", seatName: "12", seatNum: "307", codNm: "307" },
    { seatGrade: "unique", seatName: "12", seatNum: "308", codNm: "308" },
    { seatGrade: "unique", seatName: "12", seatNum: "309", codNm: "309" },
    /* 불펜지정석 */
    { seatGrade: "unique", seatName: "13", seatNum: "323A", codNm: "323A" },
    /* 외야라운지석 */
    { seatGrade: "unique", seatName: "14", seatNum: "327", codNm: "327" },
    /* 스테이인터뷰존 */
    { seatGrade: "unique", seatName: "15", seatNum: "133", codNm: "133" },
    /* 잔디석 */
    { seatGrade: "unique", seatName: "16", seatNum: "128", codNm: "128" },
    { seatGrade: "unique", seatName: "16", seatNum: "326", codNm: "326" },
    /* 필드박스(1인) */
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD1", codNm: "FIELD1" },
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD2", codNm: "FIELD2" },
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD3", codNm: "FIELD3" },
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD4", codNm: "FIELD4" },
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD5", codNm: "FIELD5" },
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD6", codNm: "FIELD6" },
    { seatGrade: "unique", seatName: "17", seatNum: "FIELD7", codNm: "FIELD7" },
    /* 미니박스 */
    { seatGrade: "unique", seatName: "18", seatNum: "M01", codNm: "M01" },
    { seatGrade: "unique", seatName: "18", seatNum: "M02", codNm: "M02" },
    { seatGrade: "unique", seatName: "18", seatNum: "M03", codNm: "M03" },
    { seatGrade: "unique", seatName: "18", seatNum: "M04", codNm: "M04" },
    { seatGrade: "unique", seatName: "18", seatNum: "M05", codNm: "M05" },
    { seatGrade: "unique", seatName: "18", seatNum: "M06", codNm: "M06" },
    { seatGrade: "unique", seatName: "18", seatNum: "M07", codNm: "M07" },
    { seatGrade: "unique", seatName: "18", seatNum: "M08", codNm: "M08" },
    { seatGrade: "unique", seatName: "18", seatNum: "M09", codNm: "M09" },
    { seatGrade: "unique", seatName: "18", seatNum: "M10", codNm: "M10" },
    /* 스카이박스 */
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY01", codNm: "SKY01" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY02", codNm: "SKY02" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY03", codNm: "SKY03" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY04", codNm: "SKY04" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY05", codNm: "SKY05" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY06", codNm: "SKY06" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY07", codNm: "SKY07" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY08", codNm: "SKY08" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY09", codNm: "SKY09" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY10", codNm: "SKY10" },
    { seatGrade: "SKYBOX", seatName: "1", seatNum: "SKY11", codNm: "SKY11" },
  ],
};
